"""Add spotify_id column to podcast table

Revision ID: 15f8d5fe2054
Revises: dfb3a19e80b8
Create Date: 2025-05-14 18:30:44.982129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f8d5fe2054'
down_revision = 'dfb3a19e80b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('publisher', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_podcast_spotify_id', ['spotify_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('image_url')
        batch_op.drop_column('publisher')
        batch_op.drop_column('spotify_id')

    # ### end Alembic commands ###
