"""add review to PodcastLog

Revision ID: 52417dec5f0f
Revises: 0cb719df6b1e
Create Date: 2025-05-16 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '52417dec5f0f'
down_revision = '0cb719df6b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast_log',
        sa.Column('review', sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast_log', 'review')
    # ### end Alembic commands ###

