"""add shared flag to PodcastLog

Revision ID: ab77064891a7
Revises: dc87b41132f6
Create Date: 2025-05-15 16:02:20.974262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab77064891a7'
down_revision = 'dc87b41132f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared', sa.Boolean(), nullable=False, server_default=sa.text('0'),))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast_log', schema=None) as batch_op:
        batch_op.drop_column('shared')

    # ### end Alembic commands ###
