"""Initial migration

Revision ID: dc87b41132f6
Revises: 93ef41f5e5e9
Create Date: 2025-05-14 23:27:07.026040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc87b41132f6'
down_revision = '93ef41f5e5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ep_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('platform', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(length=64), nullable=True))
        batch_op.drop_column('notes')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.drop_column('genre')
        batch_op.drop_column('platform')
        batch_op.drop_column('ep_name')

    # ### end Alembic commands ###
