"""add profile_pic to user

Revision ID: e0b90387dda0
Revises: e2e7bf6a05e5
Create Date: 2025-05-13 19:10:00.000000
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "e0b90387dda0"
down_revision = "e2e7bf6a05e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "profile_pic",
                sa.String(length=255),
                nullable=False,
                server_default="default.png",
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("profile_pic")
    # ### end Alembic commands ###

