"""Add auth_provider to User

Revision ID: e2e7bf6a05e5
Revises: dfb3a19e80b8
Create Date: 2025-05-13 18:43:26.303355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e7bf6a05e5'
down_revision = 'dfb3a19e80b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust!### 
   # with op.batch_alter_table('podcast', schema=None) as batch_op:
   #     batch_op.add_column(sa.Column('spotify_id', sa.String(length=120), nullable=True))
   #     batch_op.add_column(sa.Column('publisher', sa.String(length=120), nullable=True))
   #     batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
   #     batch_op.create_unique_constraint('uq_podcast_spotify_id', ['spotify_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=20), nullable=False, server_default = 'local'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('auth_provider')

    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('image_url')
        batch_op.drop_column('publisher')
        batch_op.drop_column('spotify_id')

    # ### end Alembic commands ###
