"""Add spotify_id column to podcast table

Revision ID: f4117aec7f94
Revises: e0b90387dda0
Create Date: 2025-05-14 19:11:22.593516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4117aec7f94'
down_revision = 'e0b90387dda0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('_alembic_tmp_podcast')
    #with op.batch_alter_table('podcast', schema=None) as batch_op:
     #   batch_op.add_column(sa.Column('spotify_id', sa.String(length=120), nullable=True))
     #   batch_op.add_column(sa.Column('publisher', sa.String(length=120), nullable=True))
    #   batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
      #  batch_op.create_unique_constraint('uq_podcast_spotify_id', ['spotify_id'])
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('publisher', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_podcast_spotify_id', ['spotify_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('image_url')
        batch_op.drop_column('publisher')
        batch_op.drop_column('spotify_id')

    op.create_table('_alembic_tmp_podcast',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('rating_volume', sa.INTEGER(), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.Column('genre', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('predicted_popularity', sa.FLOAT(), nullable=True),
    sa.Column('similar_to', sa.VARCHAR(length=200), nullable=True),
    sa.Column('spotify_id', sa.VARCHAR(length=120), nullable=True),
    sa.Column('publisher', sa.VARCHAR(length=120), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_id', name='uq_podcast_spotify_id')
    )
    # ### end Alembic commands ###
